name: yumquick
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version of your app: major.minor.patch+build
version: 1.0.0+1

# Define the Dart SDK compatibility range
environment:
  sdk: ">=3.0.0 <4.0.0"

# ---------------------------
# Dependencies for your app
# ---------------------------
dependencies:
  flutter:
    sdk: flutter

  # Default iOS-style icon set
  cupertino_icons: ^1.0.8

  # State management (can also use Riverpod instead)
  provider: ^6.1.2

  # Routing and navigation
  go_router: ^13.0.1

  # Payment gateway support (Razorpay)
  razorpay_flutter: ^1.3.5
  # Optional Stripe integration (uncomment if using)
  # flutter_stripe: ^9.5.0
  #http
  http: ^1.2.1
  # UI/UX enhancements
  cached_network_image: ^3.3.1      # For loading & caching network images
  flutter_spinkit: ^5.2.0           # Prebuilt loading indicators
  fluttertoast: ^8.2.4              # Toast messages
  flutter_animate: ^4.5.0           # Declarative animations
  rive: ^0.12.4                     # For animated vector assets

  # Responsive design support
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1

# -----------------------------
# Dev-only packages for testing, linting, etc.
# -----------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules to enforce good coding standards
  flutter_lints: ^4.0.0

# -----------------------------
# Flutter-specific settings
# -----------------------------
flutter:

  # Use the built-in Material Icons font
  uses-material-design: true

  # Asset directories to include in the app
  assets:
    - assets/images/    # Place images like logo, splash, onboarding, etc. here
    - assets/icons/      # Place icons used throughout the app here

  # Optional: Fonts can be added like this
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700
